.gitignore
.gitmodules

- submodule 위치 변경
- resolved: #14

[feat] submodule 위치 변경

---

.github/workflows/cd.yml
.github/workflows/ci.yml
appspec.yml
deploy/docker/Dockerfile
deploy/docker/docker-compose.infra.yml
deploy/docker/docker-compose.was.yml
deploy/scripts/beforeInstall.sh
deploy/scripts/healthCheck.sh
deploy/scripts/runNewWas.sh
deploy/scripts/stopServer.sh
deploy/scripts/switchPort.sh

- Automatic Add Assign Reviewer
-진행중
- resolved: #6

[feat] Feature Github Actions

---

.github/workflows/auto-assign-reviewer.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
build.gradle
src/main/java/org/crops/fitserver/global/filter/JwtAccessDeniedHandler.java
src/main/java/org/crops/fitserver/global/filter/JwtExceptionFilter.java
src/test/java/org/crops/fitserver/FitServerApplicationTests.java

- 에러 로그 남기기 리펙토링
- 작업중..
- resolved: #17

[feat] Chatting Server 구현중..

---

build.gradle
src/main/java/org/crops/fitserver/domain/user/constant/PolicyType.java
src/main/java/org/crops/fitserver/domain/user/controller/UserController.java
src/main/java/org/crops/fitserver/domain/user/domain/UserInfoSkill.java
src/main/java/org/crops/fitserver/domain/user/domain/UserPolicyAgreement.java
src/main/java/org/crops/fitserver/domain/user/dto/PolicyAgreementDto.java
src/main/java/org/crops/fitserver/domain/user/dto/request/UpdatePolicyAgreementRequest.java
src/main/java/org/crops/fitserver/domain/user/dto/request/UpdateUserRequest.java
src/main/java/org/crops/fitserver/domain/user/dto/response/GetPolicyAgreementResponse.java
src/main/java/org/crops/fitserver/domain/user/dto/response/UpdatePolicyAgreementResponse.java
src/main/java/org/crops/fitserver/domain/user/facade/UserFacade.java
src/main/java/org/crops/fitserver/domain/user/facade/UserFacadeImpl.java
src/main/java/org/crops/fitserver/domain/user/repository/UserPolicyAgreementRepository.java
src/main/java/org/crops/fitserver/domain/user/service/UserService.java
src/main/java/org/crops/fitserver/domain/user/service/UserServiceImpl.java
src/main/java/org/crops/fitserver/global/annotation/CurrentUser.java
src/main/java/org/crops/fitserver/global/annotation/CurrentUserId.java
src/main/java/org/crops/fitserver/global/config/SecurityConfig.java
src/main/java/org/crops/fitserver/global/config/WebConfig.java
src/main/java/org/crops/fitserver/global/exception/ErrorCode.java
src/test/java/org/crops/fitserver/domain/region/repository/RegionRepositoryTest.java
src/test/java/org/crops/fitserver/domain/school/repository/SchoolRepositoryTest.java
src/test/java/org/crops/fitserver/domain/skillset/repository/PositionRepositoryTest.java
src/test/java/org/crops/fitserver/domain/skillset/repository/SkillRepositoryTest.java
src/test/java/org/crops/fitserver/domain/user/controller/UserControllerTest.java
src/test/java/org/crops/fitserver/domain/user/repository/UserPolicyAgreementRepositoryTest.java
src/test/java/org/crops/fitserver/domain/user/repository/UserRepositoryTest.java
src/test/java/org/crops/fitserver/domain/user/service/UserServiceTest.java

- 약관 동의를 위한 로직 추가
- 없음
- resolved: #25

[feat] 약관 동의 관련 로직 추가

---

build.gradle
src/main/java/org/crops/fitserver/domain/auth/controller/AuthController.java
src/main/java/org/crops/fitserver/domain/auth/facade/AuthFacade.java
src/main/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImpl.java
src/main/java/org/crops/fitserver/domain/auth/service/OAuthService.java
src/main/java/org/crops/fitserver/domain/auth/service/impl/GoogleOAuthServiceImpl.java
src/main/java/org/crops/fitserver/domain/auth/service/impl/KakaoOAuthServiceImpl.java
src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleClientProperty.java
src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoClientProperty.java
src/test/java/org/crops/fitserver/domain/auth/controller/AuthControllerTest.java
src/test/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImplTest.java

- Redirect uri 따로 안 받고, application 설정 파일에서  가져오기로 설정
- 예시
- resolved: #

[feat] oauth login 시 redirect uri 파라미터 제거 

---

deploy/scripts/buildInfra.sh

- db 실행 확인문 수정
- 예시
- resolved: #

 #24 [fix] script error 수정

---

deploy/docker/docker-compose.infra.yml

 [fix] fix db error

---

src/main/java/org/crops/fitserver/domain/auth/controller/AuthController.java
src/main/java/org/crops/fitserver/domain/auth/dto/request/SocialLoginRequest.java
src/main/java/org/crops/fitserver/domain/auth/dto/response/SocialLoginPageResponse.java
src/main/java/org/crops/fitserver/domain/auth/dto/response/TokenResponse.java
src/main/java/org/crops/fitserver/domain/auth/facade/AuthFacade.java
src/main/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImpl.java
src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
src/main/java/org/crops/fitserver/domain/chat/dto/request/SendMessageRequest.java
src/main/java/org/crops/fitserver/domain/chat/dto/response/ImageMessageResponse.java
src/main/java/org/crops/fitserver/domain/chat/dto/response/NoticeMessageResponse.java
src/main/java/org/crops/fitserver/domain/chat/dto/response/TextMessageResponse.java
src/main/java/org/crops/fitserver/domain/chat/service/impl/MessageServiceImpl.java
src/main/java/org/crops/fitserver/global/exception/BusinessExceptionHandler.java
src/main/java/org/crops/fitserver/global/exception/ErrorResponse.java
src/test/java/org/crops/fitserver/domain/auth/controller/AuthControllerTest.java
src/test/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImplTest.java

- BindExceoption Handler 추가
- OAuth Login HTTP Method POST 로 변경
- 상세 테스트는 더 구현해보겠습니다..
- resolved:

[refactor] Oauth Login 메서드 변경,  에러메세지 구체화

---

src/main/java/org/crops/fitserver/domain/recommend/controller/RecommendController.java
src/main/java/org/crops/fitserver/domain/recommend/dto/RecommendUserDto.java
src/main/java/org/crops/fitserver/domain/recommend/dto/request/RecommendUserRequest.java
src/main/java/org/crops/fitserver/domain/recommend/dto/response/RecommendUserResponse.java
src/main/java/org/crops/fitserver/domain/recommend/facade/RecommendFacade.java
src/main/java/org/crops/fitserver/global/config/CorsConfig.java
src/main/resources/db/mariadb/data.sql
src/test/java/org/crops/fitserver/domain/auth/service/impl/KakaoOAuthServiceImplTest.java
src/test/java/org/crops/fitserver/domain/recommend/controller/RecommendControllerTest.java

- add feature of Recommend User Request Api Dos
- "dev.f-it.team" Origin Allow  
- 
- resolved: #

[fix,test,feat] fix cors error, add recommend api docs

---

build.gradle
src/main/java/org/crops/fitserver/domain/auth/controller/AuthController.java
src/main/java/org/crops/fitserver/domain/auth/facade/AuthFacade.java
src/main/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImpl.java
src/main/java/org/crops/fitserver/domain/auth/service/OAuthService.java
src/main/java/org/crops/fitserver/domain/auth/service/impl/GoogleOAuthServiceImpl.java
src/main/java/org/crops/fitserver/domain/auth/service/impl/KakaoOAuthServiceImpl.java
src/main/java/org/crops/fitserver/domain/user/domain/User.java
src/main/java/org/crops/fitserver/global/feign/oauth/google/GoogleClientProperty.java
src/main/java/org/crops/fitserver/global/feign/oauth/kakao/KakaoClientProperty.java
src/test/java/org/crops/fitserver/domain/auth/controller/AuthControllerTest.java
src/test/java/org/crops/fitserver/domain/auth/facade/impl/AuthFacadeImplTest.java
src/test/java/org/crops/fitserver/domain/auth/service/impl/GoogleOAuthServiceImplTest.java

- Oauth Login by haeder Origin 
- get social login page by header origin
- resolved: #

[refactor] refactoring OAuth APi

---

src/main/java/org/crops/fitserver/domain/file/service/S3FileServiceImpl.java
src/main/java/org/crops/fitserver/domain/matching/entity/Matching.java
src/main/java/org/crops/fitserver/domain/matching/entity/MatchingRoom.java
src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingProcessor.java
src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingScheduler.java
src/main/java/org/crops/fitserver/domain/matching/service/impl/MatchingServiceImpl.java
src/main/java/org/crops/fitserver/domain/project/constant/Constant.java
src/main/java/org/crops/fitserver/domain/project/constant/ProjectConstant.java
src/main/java/org/crops/fitserver/domain/project/constant/ProjectStatus.java
src/main/java/org/crops/fitserver/domain/project/controller/ProjectController.java
src/main/java/org/crops/fitserver/domain/project/dto/ProjectDto.java
src/main/java/org/crops/fitserver/domain/project/dto/ProjectMemberDto.java
src/main/java/org/crops/fitserver/domain/project/dto/request/UpdateProjectRequest.java
src/main/java/org/crops/fitserver/domain/project/dto/response/GetProjectListResponse.java
src/main/java/org/crops/fitserver/domain/project/dto/response/UpdateProjectResponse.java
src/main/java/org/crops/fitserver/domain/project/entity/Project.java
src/main/java/org/crops/fitserver/domain/project/entity/ProjectMember.java
src/main/java/org/crops/fitserver/domain/project/repository/ProjectMemberRepository.java
src/main/java/org/crops/fitserver/domain/project/repository/ProjectRepository.java
src/main/java/org/crops/fitserver/domain/project/service/ProjectService.java
src/main/java/org/crops/fitserver/domain/project/service/ProjectServiceImpl.java
src/main/java/org/crops/fitserver/domain/project/util/ConverterUtil.java
src/main/java/org/crops/fitserver/domain/project/util/ProjectConverter.java
src/main/java/org/crops/fitserver/domain/skillset/domain/Position.java
src/main/java/org/crops/fitserver/global/exception/ErrorCode.java
src/main/resources/db/mariadb/V1_init.sql
src/test/java/org/crops/fitserver/domain/project/controller/ProjectControllerTest.java
src/test/java/org/crops/fitserver/domain/skillset/repository/PositionRepositoryTest.java
src/test/java/org/crops/fitserver/domain/user/repository/UserRepositoryTest.java

- 내 프로젝트 관련 api 구현
- 전체적으로 매칭방 로직과 유사합니다.(비슷한 구조이기 때문)
- 이전 pr을 먼저 확인하셔야 합니다.
- 다른 부분보다 좀 더 같이 봐줬으면 하는 부분은 주석을 남겼습니다.
- resolved: #44

[feat] 내프로젝트 관련 로직 구현

---

src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingProcessor.java
src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingScheduler.java

- 스케줄러쪽 로그를 size가 0이상일 떄에만 출력하도록 수정했습니다.
- resolved: #55

[refactor] 스케줄러의 로그가 필요한 상황에서만 출력되도록 수정

---

src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingScheduler.java
src/main/java/org/crops/fitserver/domain/project/dto/ProjectMemberDto.java
src/main/java/org/crops/fitserver/domain/recommend/service/impl/RecommendServiceImpl.java
src/main/java/org/crops/fitserver/global/cache/CacheConstants.java
src/main/java/org/crops/fitserver/global/cache/CacheRepository.java
src/main/java/org/crops/fitserver/global/cache/RedisCacheRepository.java
src/test/java/org/crops/fitserver/domain/project/controller/ProjectControllerTest.java

- 프로젝트 모음에서 username이 아닌 nickname이 노출되도록 수정
- 비즈니스 코드의 레디스 의존성 분리
- 없음
- resolved: #64 
- resolved: #60

[fix] username이 아닌 nickname 노출 + redis 의존성 분리

---

deploy/scripts/healthCheck.sh

[fix] health check 60초로 증가

---

src/main/java/org/crops/fitserver/domain/recommend/repository/UserLikesRepository.java
src/main/java/org/crops/fitserver/domain/recommend/service/RecommendService.java
src/main/java/org/crops/fitserver/domain/recommend/service/impl/RecommendServiceImpl.java
src/main/java/org/crops/fitserver/domain/user/controller/UserController.java
src/main/java/org/crops/fitserver/domain/user/dto/UserProfileDto.java
src/main/java/org/crops/fitserver/domain/user/dto/response/GetUserStatusAndInfoResponse.java
src/main/java/org/crops/fitserver/domain/user/facade/UserFacade.java
src/main/java/org/crops/fitserver/domain/user/facade/UserFacadeImpl.java
src/main/java/org/crops/fitserver/domain/user/repository/UserRepository.java
src/main/java/org/crops/fitserver/domain/user/service/UserServiceImpl.java
src/main/java/org/crops/fitserver/global/socket/WebSocketAddMappingSupporter.java
src/main/resources/db/mariadb/V1_init.sql
src/test/java/org/crops/fitserver/domain/user/controller/UserControllerTest.java

[feat] user withdraw, user 정보 조회 추가

---

appspec.yml

[chore] health check script timeout 확장

---

src/main/java/org/crops/fitserver/global/socket/ChatRoomConnectListener.java

[fix] web Sokcet  user token 쿼리 파라미터로 변경

---

src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingProcessor.java
src/main/resources/db/mariadb/V2_init.sql

 #63 [fix] ChatRoomUser 생성 로직 추가

---

src/main/java/org/crops/fitserver/global/socket/service/SocketService.java

 #63 [fix] message sender 도 받기

---

src/main/java/org/crops/fitserver/domain/alarm/controller/AlarmController.java
src/main/java/org/crops/fitserver/domain/alarm/domain/Alarm.java
src/main/java/org/crops/fitserver/domain/alarm/domain/AlarmCase.java
src/main/java/org/crops/fitserver/domain/alarm/domain/AlarmType.java
src/main/java/org/crops/fitserver/domain/alarm/dto/AlarmDto.java
src/main/java/org/crops/fitserver/domain/alarm/dto/response/GetAlarmListResponse.java
src/main/java/org/crops/fitserver/domain/alarm/facade/AlarmFacade.java
src/main/java/org/crops/fitserver/domain/alarm/facade/impl/AlarmFacadeImpl.java
src/main/java/org/crops/fitserver/domain/alarm/repository/AlarmRepository.java
src/main/java/org/crops/fitserver/domain/alarm/service/AlarmService.java
src/main/java/org/crops/fitserver/domain/alarm/service/impl/AlarmServiceImpl.java
src/main/java/org/crops/fitserver/domain/chat/facade/impl/ChatRoomFacadeImpl.java
src/main/java/org/crops/fitserver/domain/chat/repository/ChatRoomUserRepository.java
src/main/java/org/crops/fitserver/domain/matching/repository/MatchingRoomRepository.java
src/main/java/org/crops/fitserver/domain/matching/scheduler/MatchingProcessor.java
src/main/java/org/crops/fitserver/domain/matching/service/impl/MatchingServiceImpl.java
src/main/java/org/crops/fitserver/domain/project/repository/ProjectRepository.java
src/main/java/org/crops/fitserver/domain/project/service/ProjectServiceImpl.java
src/main/resources/db/mariadb/ddl/V3_init.sql
src/test/java/org/crops/fitserver/domain/alarm/controller/AlarmControllerTest.java
src/test/java/org/crops/fitserver/domain/matching/service/impl/MatchingServiceTest.java

- 알림 조회,
- 알림 
- alarm list 조회 추가
- 아직 매칭 완료, 퇴장 등의 상황에서  알림 보내는 로직은 추가 안 했습니당 
-
- resolved: #57

[feat] Alarm 조회 추가

---

deploy/scripts/buildInfra.sh
src/main/java/org/crops/fitserver/domain/alarm/repository/AlarmRepository.java
src/main/java/org/crops/fitserver/domain/alarm/service/impl/AlarmServiceImpl.java
src/main/java/org/crops/fitserver/domain/chat/dto/response/ImageMessageResponse.java
src/main/java/org/crops/fitserver/domain/matching/repository/MatchingRepository.java
src/main/java/org/crops/fitserver/domain/matching/repository/MatchingRoomRepository.java
src/main/java/org/crops/fitserver/domain/project/repository/ProjectRepository.java
src/main/java/org/crops/fitserver/domain/school/repository/SchoolRepository.java
src/main/java/org/crops/fitserver/domain/skillset/repository/PositionRepository.java
src/main/java/org/crops/fitserver/domain/skillset/repository/SkillRepository.java
src/main/java/org/crops/fitserver/domain/user/repository/SocialUserInfoRepository.java
src/main/java/org/crops/fitserver/domain/user/repository/UserRepositoryImpl.java
src/main/resources/db/mariadb/ddl/V1_init.sql

- Index 추가 중
- 
- resolved: #81

 #81 [refactor] Schema Index 추가

---

src/main/java/org/crops/fitserver/domain/chat/constant/ChatMessage.java
src/main/java/org/crops/fitserver/domain/chat/controller/ChatController.java
src/main/java/org/crops/fitserver/domain/chat/domain/MessageType.java
src/main/java/org/crops/fitserver/domain/chat/facade/ChatRoomFacade.java
src/main/java/org/crops/fitserver/domain/chat/facade/impl/ChatRoomFacadeImpl.java
src/main/java/org/crops/fitserver/domain/chat/repository/ChatRoomUserRepository.java
src/main/java/org/crops/fitserver/domain/chat/service/ChatRoomService.java
src/main/java/org/crops/fitserver/domain/chat/service/MessageService.java
src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
src/main/java/org/crops/fitserver/domain/chat/service/impl/MessageServiceImpl.java
src/main/java/org/crops/fitserver/domain/user/repository/UserPolicyAgreementRepository.java
src/main/java/org/crops/fitserver/global/config/CorsConfig.java
src/main/java/org/crops/fitserver/global/config/SocketConfig.java
src/main/java/org/crops/fitserver/global/socket/WebSocketAddMappingSupporter.java
src/main/java/org/crops/fitserver/global/socket/WebSocketConnectListener.java
src/main/java/org/crops/fitserver/global/socket/service/SocketService.java

- Mesage Time -> String  변경
- JOIN, EXIT, COMPLETE 타입 추가
- Socket Controller 구조 리펙토링
- 새로운 메세지 타입 함수 ChatRoomService 의 chatRoomJoin, chatRoomLeave, chatRoomComplete 로 사용하면 됩니다
- resolved: #

[feat] Message 에러 수정

---

src/main/java/org/crops/fitserver/domain/user/dto/UserInfoDto.java
src/main/java/org/crops/fitserver/domain/user/facade/UserFacadeImpl.java
src/main/java/org/crops/fitserver/domain/user/service/UserServiceImpl.java
src/test/java/org/crops/fitserver/domain/user/service/UserServiceTest.java

#89 [fix] QA사항 수정

---

src/main/java/org/crops/fitserver/global/config/JpaConfig.java

 #81 [fix] jpa time 타입 에러 수정

---

src/main/java/org/crops/fitserver/domain/chat/service/ChatRoomService.java
src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
src/main/java/org/crops/fitserver/domain/matching/service/impl/MatchingServiceImpl.java

 #81 [refactor] complete 시 project id 응답

---

src/main/java/org/crops/fitserver/global/socket/service/MessageResponse.java

 #81 [fix] cancel ready 처리

---

src/main/java/org/crops/fitserver/global/socket/service/SocketService.java

 #81 [fix] 메세지 두 번 겟 에러 처리

---

src/main/java/org/crops/fitserver/global/socket/service/SocketService.java

 #81 [fix] Notice null 검사

---

src/main/java/org/crops/fitserver/global/socket/service/SocketService.java

 #81 [fix] Message null 검사

---

src/main/java/org/crops/fitserver/domain/chat/dto/response/NoticeMessageResponse.java
src/main/java/org/crops/fitserver/global/socket/service/SocketService.java

 #81 [fix] Notice Message type 에러 수정

---

src/main/java/org/crops/fitserver/domain/chat/domain/MessageType.java
src/main/java/org/crops/fitserver/domain/chat/service/impl/ChatRoomServiceImpl.java
src/main/java/org/crops/fitserver/global/socket/WebSocketAddMappingSupporter.java

 #81 [fix] fix error

---

src/main/java/org/crops/fitserver/domain/chat/repository/ChatRoomUserRepository.java
src/main/java/org/crops/fitserver/domain/matching/controller/MatchingController.java
src/main/java/org/crops/fitserver/domain/recommend/dto/request/RecommendUserRequest.java
src/main/java/org/crops/fitserver/domain/recommend/facade/impl/RecommendFacadeImpl.java
src/main/java/org/crops/fitserver/domain/recommend/service/RecommendService.java
src/main/java/org/crops/fitserver/domain/recommend/service/impl/RecommendServiceImpl.java

 #81 [fix] 팀원 추천 에러 수정, 강제퇴장 에러 수정

---

src/main/java/org/crops/fitserver/domain/matching/entity/MatchingRoom.java
src/main/java/org/crops/fitserver/global/mail/JavaMailManager.java

-  메일을 보낼 수 없는 버그
- host가 준비 상태가 가능한 버그 수정
- 예시
- resolved: #104

[fix] 메일을 보낼 수 없는 버그, host가 준비 상태가 가능한 버그 수정

---

deploy/scripts/stopServer.sh

 [fix] docker remove image if 수정
